version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: bp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: salob79/bp-backend:latest
    container_name: bp-backend
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/bp

  # frontend:
  #   image: salob79/bp-frontend:latest
  #   container_name: bp-frontend
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend

volumes:
  mongo-data:

