name: Frontend CI/CD

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
      SONAR_TOKEN:
        required: true
      GH_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    outputs:
      image_tag:
        description: "Frontend image tag"
        value: ${{ jobs.release.outputs.image_tag }}

jobs:
  smoketest:
    uses: ./.github/workflows/smoketest.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }} 

  ci:
    runs-on: ubuntu-latest
    needs:
      - smoketest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: sianob/bp-frontend
          ref: ${{ github.head_ref || github.ref_name }}                  # Replace with the branch where this workflow resides
          token: ${{ secrets.GH_PAT }} # Needed to access private repos
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: echo "VITE_API_BASE_URL=http://localhost:8000" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: npm run coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    permissions:
      contents: write  # Required to create release and push tags
    needs:
      - ci
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: sianob/bp-frontend
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ secrets.GH_PAT }} # Needed to access private repos
      
      - name: Fetch all tags
        run: git fetch --tags
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: salob79/bp-frontend:${{ env.VERSION }},salob79/bp-frontend:latest

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: salob79/bp-frontend:latest

      - name: Get and bump latest release version
        id: bump_version
        run: |
          # Fetch the latest release tag from the repo
          latest_tag=$(gh release list --repo sianob/bp-frontend --limit 1 --json tagName --jq '.[0].tagName')

          echo "Latest tag: $latest_tag"

          # Strip 'v' and split version parts
          version="${latest_tag#v}"
          IFS='.' read -r major minor patch <<< "$version"

          # Increment patch version
          patch=$((patch + 1))
          new_version="v$major.$minor.$patch"

          echo "New version: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create GitHub Release
        run: |
          echo "Creating release ${{ env.VERSION }} in sianob/bp-frontend..."
          gh release create "${{ env.VERSION }}" \
            --repo "sianob/bp-frontend" \
            --title "${{ env.VERSION }}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}


      - name: Log in to Docker Hub
        if: success() # Only log in if the scan passes
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: salob79/bp-frontend:${{ env.VERSION }},salob79/bp-frontend:latest
